### ISSUE TITLE
Backend Update

### ISSUE THREAD

**Issue by State307** [DFXLuna/mazeGame#18]
Alex and I made a general plan on Monday for how we want to go about the program 3 stuff. We are meeting up tomorrow to actually do all the coding so the pull request(s) should be in by tomorrow night. Just wanted to keep everyone updated.

**Comment by alexgermann** [comment]
All of the back-end for part 3 should be finished now. The only caveat is that we had to change the tile size to 100 due to Buckner formatting his raw data for size 100. This made the board slightly off center but it should be fairly easy for the front end to fix.

**Comment by DFXLuna** [comment]
Looks good. Tested on Linux and everything works. Will test on Windows in a sec.
