### ISSUE TITLE
PRESENTATION

### ISSUE THREAD

**Issue by MDFL64** [DFXLuna/mazeGame#21]
So evidently we're doing the Observer Pattern. Based on some very not academic research and my own stupid opinions, I think we should be able to get a decent amount of content out of this. Some ideas, in no particular order:
- Common names: Observer, Listener, Handler, Subscriber.
- General idea of the pattern, what it does explained in simple terms. Maybe explain that the name is counter-intuitive, since the subject pushes to the observers and not the other way around?
- Go over a bad example, like the one in the book, then show how the observer can make it better.
- A UML diagram, because why not follow the trend of saying very little by drawing little boxes on the board? (My opinions **will** get me in trouble. Just getting that out of the way now.)
- Implementations in Java: Observer/Observable, and all them event handler classes.
- Lapsed Listener Problem -- Garbage collection is fun! Who wants the honor of explaining weak references?
- Other ways to screw it up -- see the IBM article.
- How anonymous classes, lambdas can be useful for this pattern. (I mostly just want to shoehorn in a way to bait people into baiting me into setting the record straight on anonymous classes. For real though. The book actually uses an anonymous class in one of the examples!)
- Maybe conclude by saying that the pattern is related to the MVC which another group will cover later.

As for academic sources I've only got our book, the java documentation, and [this article](http://www.ibm.com/developerworks/library/j-jtp07265/) by IBM which might be acceptable. The c2 wiki is very nice but I strongly doubt it counts.

**Comment by MDFL64** [comment]
Also I don't know about Buckner's policy on this, but actual code examples that we can run for the class would be very nice.

**Comment by DFXLuna** [comment]
I vote that we get in as much trouble as possible.
Let's figure out how to divy this 5 ways
I'm thinking something like overview, pros/cons/concerns, good examples, bad examples and a wrapup

**Comment by DFXLuna** [comment]
So, just to get the ball rolling, I've assigned you all some roles for the presentation. If you think we should change a topic or if y'all wanna trade roles, go for it. Just make sure to let the rest of us know.
**Also, let's plan on having a meeting on Thursday at noon in the co sci lab to make sure we've got all this together.**
- Overview - Matt
- Pros/Cons/Considerations - Alex
- UML - Auston
- Implementation/Examples - Adam
- When to (not) use - Jared
- Wrap up/ Review - Matt

I'm not sure about putting UML as its own section. 

As far as slides go, make what you need and then send them to me before the meeting on Thursday. Remember that slides should have 100 characters or less, we're limited to 10 content slides, and that we need to keep a bibliography in ACM style.

**Comment by State307** [comment]
Sounds good, I'll be there Thursday at 12. **I promise.**

**Comment by MDFL64** [comment]
Well, I have not been feeling so super the last few days. I'll try doing some actual research tomorrow and posting my results here. Sort of skeptical about the topics, I talked to Jared today and he wasn't sure he'd be able to come up with much. Anyway, I'll post back tomorrow and let you know if I find anything useful.

**Comment by jaredf1** [comment]
Ive found a couple PDFs from the UW library that are useful, and youtube was an excellent source to describe the main features of the design pattern.

**Comment by MDFL64** [comment]
Cool. I don't know if you guys have checked yet, but the Gang of Four book has a very nice list of implementation concerns / issues that could be nice for Alex. It also lists _another_ alternative name for the pattern (dependents). I think I'm going to have enough to say by describing how to use the built-in implementations of observers, so maybe Auston could show how to code a subject/observer, if UML isn't enough?

I'll finish me research in a bit, I don't think I'll need much more than what's in course book and the java reference.

**Comment by alexgermann** [comment]
The Gang of Four book? I'm not sure I know what you're talking about  but I'll look into it. I'll be at the meeting as well. Are we limited to 10 slides total? So 2 per person?

**Comment by DFXLuna** [comment]
Gang of Four is like the OG design pattern book. And yeah, two per person

**Comment by MDFL64** [comment]
### Observers in the Java Standard Library
- java.util.Observer, Observable
  - Should we use them?
- EventListeners
  - UI (Both AWT and Swing)
  - Many other uses!

### An Example
- Three Buttons
- We want the program to respond when they are clicked.
- Naive solutions
- Using an Observer
- Improvements

Here are my sources. Not so sure about the formatting of the java documentation one.

Skrien, D. Object-Oriented Design Using Java. McGraw-Hill, New York, 2009.

Oracle Corporation. Java(TM) Platform, Standard Edition 7 API Specification, 2016. Retrieved April 14, 2016, from Oracle Corporation: https://docs.oracle.com/javase/7/docs/api/

**Comment by DFXLuna** [comment]
Here's the Powerpoint: 
[The Observer Pattern.pptx](https://github.com/DFXLuna/mazeGame/files/220139/The.Observer.Pattern.pptx)

EDIT: All good, this is the final version.

**Comment by MDFL64** [comment]
Neato, I've been trying to rehearse my part and figure out exactly how much code I want to write on the board. Hopefully I'm slightly more mentally coherent tomorrow and this won't be a full blown train wreck.

**Comment by alexgermann** [comment]
I used the textbook as well as the "gang of four" book, cited (perhaps incorrectly) here.

Erich Gamma. 1995. Design patterns: elements of reusable object-oriented software, Reading, MA: Addison-Wesley.
