### ISSUE TITLE
Program 6 Spec THE FINAL BALLET

### ISSUE THREAD

**Issue by DFXLuna** [DFXLuna/mazeGame#32]
Here's the spec: [program06.pdf](https://github.com/DFXLuna/mazeGame/files/244284/program06.pdf)

All we have to do is implement "winning". 

Also, I'm out of town on thursday so we need to come up with another meeting time. I'm open MW after Algorithms and tuesday before 2 and after 430.

**Comment by MDFL64** [comment]
After algorithms is good for me.
Between Noon and 2 and after 4:30 also works for me.

**Comment by MDFL64** [comment]
Required viewing: https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript
