### ISSUE TITLE
REFACTORING

### ISSUE THREAD

**Issue by MDFL64** [DFXLuna/mazeGame#36]
I have taken it upon myself to try unfucking things. If anyone's planning on doing anything, please **TELL ME**, or at least use my fork, because I am not requesting a merge until it's ready.

**Also** can someone else handle the rest of the front end stuff, since I'm doing this? Either Jared or one of the backend dudes. Note that I should have save order taken care of so you won't have to worry about that.

**Tuesday**:
- Moved loading logic out of messenger and back into gameboard.
- Removed specialized left/right/grid versions of most methods. Now using an enum.
- Deleted specialized versions of visual tile holders.
- Deleted offensive functions from converter class.
- Removed unused imports.

**Wednesday**:
- Renamed FileReader -> MazeReader
- Reworked tile class. It is now mostly immutable, apart from rotation, and no longer has the goofy magic number.
- Reworked board/reader. The reader now stores the initial state of the game. This seems like a sane way to do it to me.

**Friday**:
- Make the reader generate tile objects rather than really haphazard arrays. Didn't get this quite right, but is way better than it was.
- Only allow acces to tiles from MazeReader
- Moved MakeImage to GameTile
- Save order should be good. Fixed rotation issue.
- Made save use a bytebuffer. In retrospect not sure if this was so smart.

**Todo**:
- Rewrite a lot of comments as doc blocks. **[Matt]**
- Delete commented shit, fix warnings. Probably not until new features are ready. **[Anyone who wants to]**
- Review some stuff, is there anything a field that could be a local var, any method that could be static, should anything be const/final, etc. **[Anyone who wants to]**
- Consider moving drag logic to it's own class. This could have downsides, but I'm removing my self-imposed limits on new classes in the very least.
- Use GameTiles in our entire hierarchy. Don't deal with individual images and rotations if we don't have to. This should be fine now that GameTile is (mostly) immutable.
- Consider renaming the board to something more descriptive.
- Consider using points rather than individual X/Y ints. Didn't have a whole lot of luck with this the first time I tried, Java's standard libraries really are ass.
- Lots more! This is just all I can think of.

**Comment by DFXLuna** [comment]
I think that's reasonable. Let me know if there's anything I can do to help.

**Comment by MDFL64** [comment]
If you want to take a stab at anything in the "todo" section, go for it. Just remember to pull from my fork first and tell me if you do, trying to merge the changes I'm making with other edits will almost certainly piss git off.

**Comment by DFXLuna** [comment]
I'm gonna start on rewriting the comments as docs on sunday

**Comment by jaredf1** [comment]
im working on the "youve won" shit now, scheming the timing as well.

**Comment by MDFL64** [comment]
Cool. Let me know if you have any questions.

**Comment by MDFL64** [comment]
check out my mixtape

https://www.youtube.com/watch?v=Wr7XASQQweM

**Comment by jaredf1** [comment]
adam what the fuck

**Comment by MDFL64** [comment]
Alright, submitted the PR with all this crap.

Hopefully nothing is broken or too confusing. I'd like to do a bit more, but I'll pause for now so other people can do their things.

I'm willing to write a bit about my refactoring adventures in the final document if you want.

Also wrote down some simple stuff under TODO that anyone can take a stab at if they want to.

**Also according to the feedback we need to change something. I thought I followed the doc pretty well but evidently not.**

**Comment by DFXLuna** [comment]
Everything has been JavaDoc'ed.

Why does GameBoard.doRotate unconditionally return -1?

**Comment by MDFL64** [comment]
Ehhh I actually have no idea. I think there was a bit of copypastin going on with those three methods and that was left over.
