### ISSUE TITLE
BE ADVISED

### ISSUE THREAD

**Issue by MDFL64** [DFXLuna/mazeGame#37]
ROTATIONS ARE EITHER NOT BEING SAVED OR LOADED CORRECTLY. PROBABLY PROBLEM WITH SAVING CONSIDERING THE ABSOLUTE SHITSHOW THAT UNFOLDED.

**Comment by alexgermann** [comment]
I've been trying to get it to not work correctly for ten minutes and everything is working.. Do you remember what caused it to not work?

**Comment by MDFL64** [comment]
Yeah this is PROBABLY okay. I just wasn't sure after my massive slew of edits.

**Comment by DFXLuna** [comment]
I'mma close this and we can reopen if someone finds an issue with it again.
