### ISSUE TITLE
Design Discussion

### ISSUE THREAD

**Issue by MDFL64** [DFXLuna/mazeGame#4]
I wasn't sure whether to post this on Wyocourses or here, but I like Github's interface quite a lot more, so here it is. Going to repeat some stuff from my earlier PR:
- The indents should now automatically default to 2 spaces.
- If you want an indication of where 80 characters is (I think this is what Buckner wanted), you can enable a print line under "General>Editors>Text Editors>Show Print Margin".
- The git CLI can get annoying to work with. It's good to know how to use, but there are some more user friendly tools. I use SourceTree, but there are tons of others. I'd stay away from Github for Windows though, as in my experience it tends to oversimplify things and has less features. Eclipse has built in git tools, which will probably also work fine. If you right click on the project in the explorer, everything from "Team" to "Replace With" is source control stuff.

[Link to UML for Convenience](https://www.gliffy.com/go/publish/10049449)
Not asking for anything to be changed immediately, these are just my thoughts.
- Like Matt said, our biggest issue is connecting the Front and Back ends. I feel like using Main or some third system to arbitrate communication between the two might be overkill. I think that the best bet is to pass the GameWindow a reference to the backend it needs to use. I'm not sure if it should be given references to the tiles or not. Either way it's going to need to know about them, and it would be a little cleaner to deal with direct references or maybe facades than numerical ids for the tiles or something weird like that.
- I feel like the tile's position on the screen can probably just be managed by the front end. The back end probably only needs to know about the position in the, grid and if a tile is in the grid, to check for a winning state.
- Then again, maybe the backend needs to play a more active roll? So many questions. Design makes my head hurt. I just want to code the thing.
- Where should the image live? How do we cut it up? Does the backend need to know about it?
- Do we really need a drawable interface? It seems like all that could be handled by the front end independently.
- The biggest problem is that we're going to probably be doing this through UI elements that basically have a mind of their own. I should probably look into how click and drag stuff works in Java. Personally I have no problem with manually handling mouse events and drawing a bunch of stuff to a context, but that could be a bit excessive.
- Can the add/get/set methods on the game board take two ints for the row and column, instead of a single one?
- [All this stuff](https://github.com/DFXLuna/mazeGame/blob/master/src/Main.java#L28-L38) can probably be thrown in the game window class. It's pretty minor, but I figured I'd put it here anyway.

Fortunately we don't have to worry too much about most of this stuff yet, I just wanted to bring it up, or maybe ramble pointlessly about it. It seems like the most important thing this week is our design documents, so it's probably good to discuss in detail.

Sorry for the very long winded post. I'm not incredibly invested in anything I've said here. I've witnessed coding drama before, as sad as that sounds, and I know it's generally better to just pick something and roll with it than spend a ton of time arguing about slightly different ways of doing the same thing.

**Comment by DFXLuna** [comment]
I agree that it'll be best to just pass the necessary backend pieces to the front end, I think the biggest question is how. 

We could create a manager class for all the drawable objects but that gets messy when trying to figure out where a specific tile is located (either off to the side or on the board) but it's super slick when doing things to the entire set of drawable objects.

Another solution would be just giving the front direct access to the tiles. This would make it much easier to manage the tiles position both on screen and in arrays. The issue with this would be if the front end and back end try to mess around with the same tile and screw up the state. Maybe we have the tiles not exclusively part of the front or back and then allow both of them to access the tile through a set of public methods. I like this solution a little more than the manager because it keeps the code simple.

We only need the drawable interface if we want to have each tile be responsible for its own drawing. However, that depends on how you'd like to implement the front end. I would advise we figure out the most clean way to implement the front and then build the back around making that happen.

We can definitely change the add/get/set methods to take two ints, that was the original intention but i miswrote them.

As far was where code goes, I trust your judgement

**Comment by MDFL64** [comment]
I've thought it through a bit more, and I feel like it would be best to just use the same tile objects on the front and back ends, so they can be responsible for their own drawing. Java doesn't seem to provide any kind of draggable UI component, so making front end versions that are based off of UI components would probably be a waste of time. I also feel like having seperate versions for the front end could get messy, since we'd have to figure out what has to communicate with what. We can just pass a drawing context to each tile and the board, and avoid the hassle. I guess we'll try to get that much done tomorrow, and avoid going overboard on anything else. I don't want to step on the backend peoples' toes.

The biggest issue with this is protection-- we don't want the front end to be able to break the state of the game, so I feel like it might be good to just leave everything to deal with the state as private methods in the backend class, and don't give the tiles public stuff like "Set Position In Board" and "Set Correct Position". I'm sure there are still issues with this, but I feel like it's the best way to start. The default "package protected" access level might be our friend here.

**Comment by MDFL64** [comment]
Alright, I'm going to re-post the message from my PR, since a closed PR isn't the bast place for potentially important information...

> Jared and myself wrote the frontend. It does everything expected for the first version, so far as I can tell. It doesn't display very well on my tiny laptop screen but it should be good.
> 
> **Concerns:**
> - We might need something more extensive for GameBoard and GameTile to inherit from, since they both have a position on the screen.
> - Not sure what we should do with all the try/catches in the main file.
> 
> **Sorry for:**
> - The single giant commit
> - Possibly changing the base way more than Buckner will be happy with.
> - Using lambda functions -- I saw an opportunity and I went for it. There's another place I'd really like to use one, but I'll refrain for now...
> 
> If you have any concerns, please tell me. I need to do a LOT of homework tonight, so that's off the table, but I'm willing to adjust this tomorrow if you think it's necessary. I don't know how much you want to get done on the backend... There will totally be some concerns linking them up, but I don't think we have to worry about that for now. I think we still have to get some design documents drawn up. Not sure when we're going to do that.

Jared said he was going to mess around with the code and see if there's anything he can improve.

If the backend people want to get started, I think you guys can mostly just implement the stuff from the UML in the board and tiles -- Stuff like `GameBoard::setTileInGrid(Tile,int,int)`, `GameBoard::removeTileFromGrid(Tile)`, and `private bool GameBoard::checkHasWon()`, or whatever you want to call them. When you're done the game still won't be playable, but we'll have some kind of framework to link the frontend to. You should try to keep it self-contained if at all possible, so the front-end hopefully can't break the game state.

We still need to write up some kind of design document, IIRC. I have plenty of free time tomorrow if some of you want to meet up and do that.

I assume @DFXLuna is going to be turning the assignment in?

**Comment by DFXLuna** [comment]
I'll handle the design document, you've already done at least your fair share this week. I'll just update the uml to reflect the current project and submit it with the most current code as of tonight

**Comment by alexgermann** [comment]
Auston and I did some work on the back-end today, but we have some questions as to the implementation of the front-end and back-end relationship. We weren't quite sure where to go with the code as some assumptions we had made as a group earlier (mostly with the different arrays and how they're handled) didn't seem to be applicable anymore. 

One or both of us will submit a commit later as we have been working on a computer that doesn't have GitHub. Hopefully we can either meet and work these design issues out or just discuss it on here.

**Comment by DFXLuna** [comment]
If you guys can, consolidate the code into one pull request. Also, we should all get together this week and figure out exactly how the front and back ends will be interacting. I'm open Saturday, Sunday, Tuesday and Thursday. I'll also post a copy of this in Wyocourses.

**Comment by State307** [comment]
I will be in Gillette for the weekend but I could make it back by 3ish on Sunday if needed.

**Comment by MDFL64** [comment]
The weekend is fine for me, but I only have noon-3 free on Tuesday and Thursday. Tuesday night should work for me, but not Thursday.
