### ISSUE TITLE
ANOTHER HEADS UP

### ISSUE THREAD

**Issue by MDFL64** [DFXLuna/mazeGame#40]
Final is due Wednesday afternoon, not Wednesday night, IIRC.

You people probably already knew that but it came as kind of a shock when I checked.

**Comment by DFXLuna** [comment]
@alexgermann  @state307 @Jaredf1

I'm submitting this tonight around 10PM unless there's something we still need to finish.

**Comment by MDFL64** [comment]
Alright then. I'll give the project a final look before then, I think I might still need to fix something from last time.

Planning docs look good to me. Not sure if Buckner wants anything more substantial to document the overall process, though. Also, I didn't realize you actually generated Javadocs, that's great.

**Comment by MDFL64** [comment]
Things are not working so well for me, not sure what the problem is. Also not sure what Buckner was complaining about in the grading of the last one. I guess I could clear the board when you attempt to load an invalid maze.

**Comment by State307** [comment]
What is not working?

**Comment by MDFL64** [comment]
Maze files in the repo were not updated, and the thing I had to display errors didn't work sometimes.

Working okay now.

**Comment by MDFL64** [comment]
So are we supposed to actively be showing the time the game has been played? Assignment doesn't say anything about it, and I'd rather not do it if not necessary.

**Comment by MDFL64** [comment]
Assignment also says this, wondering if what we have is good.

> This document needs to be well-integrated, not just putting
> all the documents into one. Consider it an essay and act accordingly. It should include any
> UML diagrams or other non-text planning documents.

**Comment by State307** [comment]
Sweet. And I don't believe we need to actively show the time, we just need to display it when the game is completed. 
Also, the way the timer is set up currently it will continue timing the user even when they are in a menu. Not sure I saw anywhere in the assignment specifying that this would be a problem, but just keep it in mind if the times are coming out higher than expected when testing.

**Comment by MDFL64** [comment]
Cool. I have a dead language to study and zero intention of doing any more than I have to tonight. Going to test that stuff, just need to grab a bigger moniter, damn laptop is not doing it for me.

**Comment by MDFL64** [comment]
Can't find my SOBing HDMI adapter, guess I have to load it onto my desktop.

**Comment by MDFL64** [comment]
Yeah there are some persisting issues.

**Comment by DFXLuna** [comment]
As far as docs go, he sent out an email and, as far I can tell, what we have is fine.

I think I only updated the default.mze earlier today.

If I need to hold off on submitting until tomorrow, I can.

**Comment by MDFL64** [comment]
Alright, I just need to fix both the timing and the win check. Should be done within an hour.

**Comment by DFXLuna** [comment]
Great. Thanks for your hard work.

**Comment by alexgermann** [comment]
What exactly is wrong?

**Comment by MDFL64** [comment]
Timing works and has been tested with saving. I have no clue what was going on with it but I basically just re-wrote it.

Issue with testing if won was just a simple logical error.

Now I have to open up everything I edited in sublime and fix indents because fuck notepad++ forever. 

I'd recommend testing it yourselves, if possible.

**Comment by MDFL64** [comment]
pr ready
