### ISSUE TITLE
Testing Win Condition

### ISSUE THREAD

**Issue by DFXLuna** [DFXLuna/mazeGame#41]
Does anyone happen to know a feasible way to test the the win condition feature?

**Comment by ghost** [comment]
You may need to do something with an if else statement.
(Sorry if it doesn't help).

`if(playerScore >= 1000) {
System.out.println(playerName + " has won the game");
} else {
return 0;
}`

**Comment by alexgermann** [comment]
Lol at that comment ^

Matt, I already implemented testing for win conditions. I told Jared and Auston but forgot to post it on here. It's in my repository.

**Comment by DFXLuna** [comment]
@alexgermann what's the function called?

**Comment by alexgermann** [comment]
determineIfWon() in gameBoard and Messenger
