### ISSUE TITLE
Buckner Feedback on Submission 1

### ISSUE THREAD

**Issue by DFXLuna** [DFXLuna/mazeGame#9]
Here's Buckner's feedback on our first submission. We messed up pretty bad, but the good news is that he'll let us resubmit it.

The biggest problem is that at least one of us hasn't fixed our IDE to have 80 character lines and use 2 tabs instead of spaces. I'm not sure why because we have the Eclipse settings file with these settings in the repo. Either way, each of you needs to verify your settings even if you're 100% sure you have them.

The good news is that I've reformatted the files, reworked the planning documents  

WHAT YOU NEED TO DO.
- Check your IDE and make sure you're using 2 spaces instead of tabs. If you don't know how to do this, ask me. Make sure you also have 80 character lines.
- Go through the files you've worked on and sign your comments with your initials
- Front end guys check out the code that doesn't compile for Buckner. I don't know why it doesn't compile for him; it compiles for me just fine. It looks like his compiler is having trouble with the functor. Since the specific functor syntax you used is only available in Java 8, I'm assuming he's not on Java 8.

> Group L
> PROGRAM 01
> Grade:   32 / 100
> 
> If you fix the problems and email me the fixed files, I will regrade this.
> 
> The project document says that you are NOT to submit ANY .class files. 
> (-3 points)
> 
> And I certainly don't want all the git files, the eclipse files or any of the
> other noise. 
> 
> The planning document is too minimal. Apparently (from the doc) you had someone
> create a UML and assign some roles. And never met again, talked, anything. 
> (-10 points)
> 
> It was nice to see that I was the author of your program.  Could you not spend 5
> minutes and fix this? I did not say that you could not modify my code, only that
> it was a starting point. In class I did say I did not want you to scrap
> everything and get some game off the web. But the comments? Comments are
> important in the code for maintainability. (-5 points) 
> 
> You did not fix things so that lines are NOT more than 80 characters wide
> (prefer 78 as the wrapmargin).  Please fix your IDE so that indentations are
> less that 4 spaces (I prefer 2 but 3 is okay) and NOT TABS. That means do not
> allow tabs to be used as indentation devices. FIX THE IDE was in the project
> document and I talked about this in class. Make sure this is correct for next
> time. 10 points off next time if you don't fix it. 
> 
> Comments. You should have a comment header in every file (similar to that from
> 1030) that lists/specifies the group. Comments should be "signed" so who made
> them can be determined. 
> 
> Program won't compile. (-50 points)
> 
> GameWindow.java:84: error: ')' expected
>       btn_new.addActionListener((ActionEvent e) -> System.out.println("New Game"));
>                                             ^
> GameWindow.java:84: error: illegal start of expression
>       btn_new.addActionListener((ActionEvent e) -> System.out.println("New Game"));
>                                                  ^
> GameWindow.java:84: error: ';' expected
>       btn_new.addActionListener((ActionEvent e) -> System.out.println("New Game"));
>                                                                                  ^
> GameWindow.java:88: error: ')' expected
>       btn_reset.addActionListener((ActionEvent e) -> System.out.println("Reset"));
>                                               ^
> GameWindow.java:88: error: illegal start of expression
>       btn_reset.addActionListener((ActionEvent e) -> System.out.println("Reset"));
>                                                    ^
> GameWindow.java:88: error: ';' expected
>       btn_reset.addActionListener((ActionEvent e) -> System.out.println("Reset"));
>                                                                                 ^
> GameWindow.java:92: error: ')' expected
>       btn_quit.addActionListener((ActionEvent e) -> System.exit(0));
>                                              ^
> GameWindow.java:92: error: illegal start of expression
>       btn_quit.addActionListener((ActionEvent e) -> System.exit(0));
>                                                   ^
> GameWindow.java:92: error: ';' expected
>       btn_quit.addActionListener((ActionEvent e) -> System.exit(0));
>                                                                   ^
> 9 errors

**Comment by jaredf1** [comment]
Well that could have gone better.

**Comment by MDFL64** [comment]
Cool. I'm _almost_ positive he told to use Java 8, or 1.8, and as far as I can tell those are synonymous, but fixing this shouldn't be hard.

I sort of suspected that we would need more substantial planning stuff but that's my fault as much as anyone else's for not saying anything about it.

Looks like the tabs were in the code submitted by Alex and Austin. Did Eclipse ignore the settings I made or did you guys use something else? I had Eclipse on the "display all characters" mode, so I could see spaces, tabs, and linefeeds. As annoying as that setting is, it might be a good thing to prevent this from happening again, and should be helpful if you guys need to track down those tabs to fix them.

The line over 80 characters was probably my fault, I think it was one of the lambda expressions we're going to remove anyway. Overall I'm still pretty perplexed by these style requirements.

I don't have git or eclipse on this box yet. I'll fix our part and PR tomorrow, if that's okay with everyone.

Anyone know when we should meet for the next part? I'm not going to be in town until Monday. On MWF I'm free after 2. On Tuesday and Thursday I'm free from Noon to 3. Evenings work every day except Thursday.

**Comment by DFXLuna** [comment]
Yeah, I also thought he said we were on Java 8, but whatever.

The latest commit (c7226452e530d25aa2757d79d8d91986f002a4a0) should have the tab/spaces and characters/line formatted correctly.

I'm open Tuesday 12-3 an after 5. Thursday I'm open all day.

**Comment by jaredf1** [comment]
Im open on tuesday/thursday before 1:20 and after 2:30.

**Comment by State307** [comment]
I am open most any time after Tuesday.

**Comment by State307** [comment]
I am open almost any time after Tuesday

**Comment by DFXLuna** [comment]
Alright, we'll meet thursday at noon in the Cosci lab.

**Comment by jaredf1** [comment]
sounds good

**Comment by MDFL64** [comment]
I feel like we should probably have a good idea of what we want to get done when we meet, since we're meeting so late in the week.

Also Lambda expressions evidently don't create anonymous class files, which is odd since Java seems to treat them as a shorthand for anonymous classes rather than real first-class functions. Not that any of this is important, I was just curious after the rant about them today.

**Comment by DFXLuna** [comment]
Alright, I've resubmitted program 1. As far as our next meeting goes, we really just need to figure out what the front end needs from the back end and how that interaction is going to play out.

**Comment by alexgermann** [comment]
Sorry, I didn't see this discussion continued. Fixed the tabs and line width now. I had fixed it before but apparently you have to make a separate profile on eclipse for the changes to actually save. I will be at the meeting tomorrow.
